;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="HitReaction",DevComment="")
+GameplayTagList=(Tag="Item.Weapon.BareHand.Fist",DevComment="")
+GameplayTagList=(Tag="StateTree.Linked.BaseBoss.Attack",DevComment="Base boss Attack linked StateTree override slot.")
+GameplayTagList=(Tag="StateTree.Linked.BaseBoss.Search",DevComment="Base boss Search linked StateTree override slot.")
+GameplayTagList=(Tag="StateTreeEvent.Enemy.DodgeThreatDetected",DevComment="Enemy dodge request event emitted when a threat action is detected.")
+GameplayTagList=(Tag="StateTreeEvent.HitReaction",DevComment="")

