#pragma once

#include "NativeGameplayTags.h"

namespace MVGameplayTags
{
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Player_P1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_NPC_Enemy_E1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_NPC_Enemy_NamelessPuppet);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_NPC_Neutral_N1);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_HitReaction_ApplyDamage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Command_Event_HitReaction_ApplyDamage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Choice_Entry);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Flow_Step);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Menu);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Menu_Entry);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Menu_Entry_Checkpoint_LevelUp);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Menu_Entry_Checkpoint_NoTravelTargets);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Menu_Entry_Checkpoint_Rest);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Menu_Entry_Checkpoint_Storage);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Menu_Entry_Checkpoint_Travel);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Menu_Page);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Menu_Page_Checkpoint);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(Interaction_Menu_Page_Checkpoint_Travel);
	UE_DECLARE_GAMEPLAY_TAG_EXTERN(StateTreeEvent_Enemy_Hit);
}
